module.exports = {
  name: 'Berker Erol',
  title1: 'Senior Frontend Developer',
  printContacts: {
    'Address:': `<span class="fas fa-map-marker-alt screen" aria-hidden="true" style="padding-right: 0.7em;"></span><span>Brighton, England</span>`,
    'Github:': `<span class="fab fa-github screen" aria-hidden="true" style="padding-right: 0.5em;"></span>
                  <a href="https://github.com/berkererol">
                  <span class="print">github.com/berkererol</span>
                  <span class="screen">Github</span>
                </a>`,
    'Linkedin:':
      '<span class="fab fa-linkedin screen" aria-hidden="true" style="padding-right: 0.7em;"></span><a class="screen" href="https://www.linkedin.com/in/berkererol/">Linkedin</a><a class="print" href="https://www.linkedin.com/in/berkererol/">linkedin.com/in/berkererol</a>',
    'Phone:': `<span class="fas fa-mobile-alt screen" aria-hidden="true" style="padding-right: 0.7em;"></span>07570-677384`,
    'Email:':
      '<span class="fas fa-paper-plane screen" aria-hidden="true" style="padding-right: 0.7em;"></span><a href="mailto:berkererol@gmail.com">berkererol@gmail.com</a>',
    'Website:':
      '<span class="fas fa-link screen" aria-hidden="true" style="padding-right: 0.7em;"></span><a href="https://berkererol.com/">Portfolio</a>',
  },
  skills: [
    ['TypeScript'],
    ['JavaScript'],
    ['Adobe Suite'],
    ['Figma'],
    ['Angular v21'],
    ['Node JS'],
    ['React v19'],
    ['Redux'],
    ['User Research'],
    ['UI Design'],
    ['Wireframing'],
    ['RxJS'],
    ['HTML'],
    ['C#'],
    ['SASS'],
    ['Design systems'],
    ['CSS'],
    ['Jest'],
    ['Material UI'],
    ['Storybook'],
    ['UI Development'],
    ['French'],
    ['Prototyping'],
    ['.NET Core],
    ['Azure Services'],
    ['SQL'],
  ],
  plays: [
    {
      title: 'Senior Frontend Developer',
      company: 'The BoxOffice Company',
      location: 'Glasgow, UK (Remote)',
      website: 'https://company.boxoffice.com/',
      time: 'August 2023 - present',
      badges: [
        'React',
        'Redux',
        'Redux Saga',
        'TypeScript',
        'Jest',
        'C#',
        '.NET Framework',
        'Sentry',
        'Google Tag Manager',
        'Google Analytics',
      ],
      contents:
        'Lead frontend developer of the Boost ticketing project, the application behind millions of movie tickets sold each year.',
      points: [
        'Spearheaded the development of new features and expanded business capabilities while coding in TypeScript and using React, Redux, and Jest.',
        'Added new backend services that handle complex API business logic in C#, using the .NET framework.',
        'Integrated Sentry plug-in for real-time bug tracking, skillfully identifying and rectifying complex issues, thereby substantially improving product reliability.',
        'Collaborated with the designers to resolve UX issues in the edge case scenarios, provided corrections, and overall facilitated the design process.',
      ],
    },
    {
      title: 'User Experience Designer (Design System Owner)',
      company: 'Genetec',
      location: 'Montréal, Canada',
      website: 'https://www.genetec.com/',
      time: 'May 2022 - May 2023',
      badges: [
        'Figma',
        'Design Systems',
        'Design Tokens',
        'Prototyping',
        'Wireframing',
        'UX Design',
        'UI Design',
        'Stencil JS',
        'Web Components',
      ],
      contents:
        'Owner UX designer of the Gelato design system, the main reference guide used by UX designers and frontend developers to build new product features.',
      points: [
        'Researched, documented and designed new interface components (e.g. Date Input, Alert, Progress) and supervised UX developers to ensure 100% consistency between Figma and component package.',
        'Lead the Design Token initiative, which leverages tokens in Figma to accelerate product-specific variations in the UI.',
        'Inspected new UX prototypes for compliance to the design system, and refined current components in response to new feature requirements.',
      ],
    },
    {
      title: 'Frontend Developer',
      company: 'Behaviour Interactive',
      location: 'Montréal, Canada',
      website: 'https://www.bhvr.com',
      time: 'November 2021 - April 2022',
      badges: [
        'React',
        'TypeScript',
        'Javascript',
        'Cypress',
        'CSS & SASS',
        'Node JS',
        'Docker',
        'Amazon S3',
        'OAuth 2.0',
        'Steam API',
      ],
      contents:
        'Frontend developer and UX designer assigned for Behaviour Account, a web platform where gamers manage their account.',
      points: [
        'Maintained frontend code of the current Behaviour Account website, where gamers can synchronize their progression in the award-winning Dead by Deadlight game on different platforms (Steam, Stadia).',
        'Led the UX design process (research, design and code implementation) of a major promotion initiative for an upcoming new game, where gamers will redeem a game reward on the web application.',
        'Refactored the entire frontend application using React for mobile use, established a design system, and implemented internationalization that supports 12 languages.',
      ],
    },
    {
      title: 'Frontend Developer',
      company: 'Intact Insurance',
      location: 'Montréal, Canada',
      website: 'https://www.intact.ca',
      time: 'April 2021 - October 2021',
      badges: [
        'Angular',
        'Nx',
        'TypeScript',
        'Javascript',
        'Storybook',
        'Cypress',
        'Jenkins',
        'Sass',
        'CSS',
        'Node JS',
        'Docker',
        'OpenShift',
        'Kubernetes',
        'Micro Frontends',
      ],
      contents:
        "Angular developer for building new UI features for Intact's web application for quote generation, used by millions throughout Canada.",
      points: [
        'Developed new components using Angular and Storybook while applying reactive patterns in TypeScript (RxJS).',
        'Built new standalone libraries within the Nx framework for migrating towards micro frontend architecture.',
        'Implemented comprehensive end-to-end tests with Cypress and increased code coverage from 85% to 100%.',
        'Independently deployed code to testing environments and prepared Git branches for releases.',
      ],
    },
    {
      title: 'Full Stack Web Developer',
      company: 'OneSpan',
      location: 'Montréal, Canada',
      website: 'https://www.onespan.com',
      time: 'January 2020 - April 2021',
      badges: [
        'Angular',
        'React',
        'TypeScript',
        'Javascript',
        'Storybook',
        'Material UI',
        'Jenkins',
        'BASH',
        'Karma',
        'Node JS',
        'Docker',
        'OpenShift',
        'Kubernetes',
        'CSS',
        'JSS',
        'SASS',
      ],
      contents:
        'Developer in the Secure Agreement Automation team, a SaaS application for digital authentication, e-signature and audit trail generation for contracts, used by most credit companies in EU.',
      points: [
        'Written bash scripts which cut down new client onboarding time from months to several weeks.',
        'Developed web accessibility-compliant (ADA) UI components in Angular, with SASS and Material UI.',
        'Implemented unit tests with Karma and Jasmine, and increased code coverage to 100%.',
        'Integrated frontend application to Gitlab CI/CD pipelines and performed regular deployments using Docker, Kubernetes and OpenShift.',
      ],
    },
  ],
  project: [
    {
      header: 'Mnemosyne',
      website: 'https://github.com/berkererol/Mnemosyne',
      skills: [
        'Javascript',
        'React',
        'Express JS',
        'PostgreSQL',
        'CSS',
        'Unsplash API',
        'Merriam-Webster Dictionary API',
        'Heroku',
      ],
      contents: `Flash card application
      that allows the user learn
      and memorize any
      word, and share these cue
      cards with their peers.
      I created the user
      interface, developed
      React components,
      and integrated APIs.`,
    },
    {
      header: 'User Inteface Design for Cook It',
      website:
        'https://www.behance.net/gallery/87084299/Cook-It-User-Interface',
      skills: [
        'Figma',
        'Affinity Designer',
        'Adobe Illustrator',
        'Adobe Photoshop',
        'Canva',
      ],
      contents: `Development of a new design system for the new menu, and the rewards program for this Montreal start up.`,
    },
    {
      header: 'Architecture Projects',
      website: 'https://https://berkererol.myportfolio.com/architecture-projects',
      skills: [
        'Rhinoceros 3D',
        'Autodesk Autocad',
        'Autodesk Revit',
        'Autodesk 3Ds Max',
        'Vray Render',
        'Adobe Illustrator',
        'Adobe Photoshop',
        'Canva',
        '3D Rapid Prototyping',
        'CNC milling',
      ],
      contents: `Selection of architecture projects I have worked on.`,
    },
  ],
}
